version: '3'

services:
    db:
        image: postgres
        environment:
            - POSTGRES_DB=db
            - POSTGRES_PASSWORD=admin
            - POSTGRES_USER=admin
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"

    web:
        build: .
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
